---
title: "NCAA S&P+ 2005-2018"

output: html_document
runtime: shiny
---
  
```{r setup, include=FALSE}
library(tidyverse)
library(stringr)
library(shiny)


load("Colors.rda")
load("SnP.rda")

Colors = Colors %>%
  select(1:3)

Teams  = SnP_Full %>%
  filter(Yr == 2018) %>%
  select(Team, Conf)

confs_1 = unique(SnP_Full %>% filter(Clvl == 1 & Yr == 2018) %>% .$Conf)
confs_2 = unique(SnP_Full %>% filter(Clvl == 2 & Yr == 2018) %>% .$Conf)
confs_3 = "Ind"

confs = list(confs_1, confs_3, confs_2)

choice_list = list("Power 5" = list(confs_1),
                   "Independent" = list(confs_3),
                   "Mid Major" = list(confs_2))


for(i in 1:length(confs)){
  for(j in 1:length(confs[[i]])){
    choice_list[[i]][[j]] = Teams %>% filter(Conf == confs[[i]][[j]]) %>% .$Team
  }
  names(choice_list[[i]]) = confs[[i]]
}



```

```{r}
YrConfAvg = SnP_Full %>%
  group_by(Yr, Conf) %>% 
  summarise_at(vars(matches("val")), mean) %>% 
  left_join(SnP_Full %>% select(Conf,Clvl_f ) %>% unique(), by = "Conf")
  
colnames(YrConfAvg)[3:6] = str_replace(colnames(YrConfAvg)[3:6], "_val", "_Cavg")

```

```{r }
inputPanel(
  selectInput("ConfLvl", label = "Clvl",
              choices = list("Level" = c("Power 5", "Mid Major"))
  )

)
renderPlot(
YrConfAvg %>% filter(Clvl_f == input$Clvl) %>% 
  ggplot(aes(Yr, SnP_Cavg)) + 
  geom_hline(yintercept = 0, color = "black", alpha = 0.4) +
  geom_point(aes(color = Conf, fill = Conf), shape = 21) +
  geom_line(aes(group = Conf, color = Conf), size = 1) + 
  facet_wrap(~Clvl_f, ncol = 2) +
  scale_x_continuous(breaks = 2005:2018, labels = str_extract(2005:2018,"\\d{2}$"),
                     limits = c(2005, 2018)) +
  scale_y_continuous(breaks = seq(-40,40, by = 20), limits = c(-40, 40)) +
  theme_bw() +
  theme(panel.grid.minor = element_blank())
)
```


```{r WL, echo = F}

inputPanel(
  selectInput("Team", label = "Team",
              choices = choice_list,
              selected = "UCLA"
  )

)
renderPlot(
  ggplot(data = SnP_Full %>% filter(Team == input$Team), aes(x = Yr)) +
    geom_line(aes(y = SnP_Cavg), color = 'grey', alpha = 0.8) +
    geom_hline(yintercept = 0, lty = 2) +
    geom_line(aes(y = SnP_val),
              color = Colors %>% filter(Team == input$Team) %>% .$Color_1,
              size = 1) +
    geom_point(aes(y = SnP_val),
              color = Colors %>% filter(Team == input$Team) %>% .$Color_1,
              size = 2) +
    scale_x_continuous(breaks = 2005:2018, labels = str_extract(2005:2018,"\\d{2}$"),
                       limits = c(2005, 2018)) +
    scale_y_continuous(breaks = seq(-40,40, by = 20), limits = c(-40, 40)) +
    theme_bw() +
    labs(x = "Year", y = "S&P+ Rating",
         title = str_c("S&P+ Ratings 2005-2018 for ",input$Team),
         subtitle = str_c(Teams %>% filter(Team == input$Team) %>% .$Conf,
                          " Conference Average listed in grey"))  +
    theme(panel.grid.minor = element_blank())

)

```

```{r}
inputPanel(
  selectInput("Conf", label = "Conf",
              choices = list("Conference" = confs),
              selected = "Pac12"
  )
  selectInput("Stat", label = "Stat", multiple = T,
              choices = list("S%P+" = c("Overall", "Offense", "Defense"))
              )

)
renderPlot(
  ggplot(data = SnP_Full %>% filter(Conf == input$Conf), aes(x = Yr)) +
    geom_line(aes(y = SnP_Cavg), color = 'grey', alpha = 0.8) +
    geom_hline(yintercept = 0, lty = 2) +
    geom_line(aes(y = SnP_val, color = Team),
              size = 1) +
    geom_point(aes(y = SnP_val, color = Team),
              size = 2) +
    scale_x_continuous(breaks = 2005:2018, labels = str_extract(2005:2018,"\\d{2}$"),
                       limits = c(2005, 2018)) +
    scale_y_continuous(breaks = seq(-40,40, by = 20), limits = c(-40, 40)) +
    scale_color_manual(values = Colors %>% filter(Conf == input$Conf) %>% .$Color) +
    theme_bw() +
    labs(x = "Year", y = "S&P+ Rating",
         title = str_c("S&P+ Ratings 2005-2018 for ",input$Team),
         subtitle = str_c(Teams %>% filter(Team == input$Team) %>% .$Color_1,
                          " Conference Average listed in grey"))  +
    theme(panel.grid.minor = element_blank())

)
```

